#! /bin/sh

panel &

bspc monitor -d I II III IV V K

for desktop in $(bspc query -D); do
  bspc config -d $desktop border_width 2;
  bspc config -d $desktop window_gap 3;
done

bspc config top_padding		 14

bspc config split_ratio          0.505
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config leaf_monocle	 true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
