#!/bin/sh

panel &

bspc monitor -d I II III IV M K

for desktop in $(bspc query -D); do
  bspc config -d $desktop border_width 1
  bspc config -d $desktop window_gap 2
done

bspc config top_padding		 14

bspc config split_ratio          0.505
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config leaf_monocle	 true

bspc rule -a KeePass2 desktop='^6'
bspc rule -a Thunderbird desktop='^5'
